# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
	imports = [
		inputs.nixos-hardware.nixosModules.common-cpu-intel
		inputs.nixos-hardware.nixosModules.common-pc-laptop
		inputs.nixos-hardware.nixosModules.common-pc-laptop-ssd
	];

	boot.initrd.availableKernelModules = [ "sd_mod" "sr_mod" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ ];
	boot.extraModulePackages = [ ];

	nixpkgs.hostPlatform = "x86_64-linux";
}
